### ISSUE TITLE
Dell M4400 ALPS touchpad.

### ISSUE THREAD

**Issue by mzs112000** [arnoldthebat/chromiumos#147] opened 2018-02-15 03:45 UTC
So I got Chromium OS to run on my M4400(thanks for the NVidia support!), however, touchpad does not work. Is there a way to fix on Chromium 64?

**Comment by arnoldthebat** [comment] 2018-02-15 19:28
duplicate of 128

**Closed by arnoldthebat** 2018-02-15 19:28 UTC
