### ISSUE TITLE
RTL8188EU not working

### ISSUE THREAD

**Issue by ManasMalla** [arnoldthebat/chromiumos#189] opened 2018-08-22 10:37 UTC
I am not able to use chromium os because as sons as i boot into it from usb it asks to connect to wifi, my wifi usb sv ( rtl8188eu) is not being detected. please fix this issue and please send me the link to the chromium os file after keeping the files for rtl8188eu 
my email id - learnwithsuperoreo@gmail.com
Waiting to use it
Kindly look after it quicky
Thanking you ,
Manas Malla

**Comment by yenon** [comment] 2018-09-17 12:56
I'm having the same issue on my Acer Switch Alpha.

**Comment by arnoldthebat** [comment] 2018-11-27 20:34
Should be fixed in R71. Please test and feedback

**Closed by arnoldthebat** 2018-11-27 20:34 UTC

**Comment by ManasMalla** [comment] 2019-02-10 04:21
Pls send link for r71

**Comment by yenon** [comment] 2019-04-02 08:08
It's working as intended now, thanks for the fix!
