### ISSUE TITLE
Google Play store is not opening

### ISSUE THREAD

**Issue by ghost** [arnoldthebat/chromiumos#140] opened 2017-12-15 16:46 UTC
CHROMIUMOS ENHANCED SPECIAL BUILD – R62-9901.B has a problem with google play store, Google play store is not opening

**Comment by NexusX44** [comment] 2017-12-19 00:45
Have same problem on Dell XPS 15 9550, prompted to sign out and update over and over again

**Comment by DEaton66** [comment] 2017-12-31 18:46
Have same problem on Dell Latitude E6540, prompted to sign out and update over and over again

**Comment by arnoldthebat** [comment] 2018-01-08 19:26
It wont work yet. Detail https://arnoldthebat.co.uk/wordpress/2017/08/28/chromiumos-enhanced-special-build-r60-9592-b/

**Comment by arnoldthebat** [comment] 2018-09-10 17:55
Duplicate of #179

**Closed by arnoldthebat** 2018-09-10 17:55 UTC
Labels: bug, enhancement
