### ISSUE TITLE
Play Store didn't open on Last Build Special

### ISSUE THREAD

**Issue by emper0r** [arnoldthebat/chromiumos#174] opened 2018-06-10 17:38 UTC
Hi, 
I can installed fine into laptop ASUS K550, the only issue I see is this one as far I know for now.
I'm try to open play store on ChromiumOS last build Special, June 2018 Camd64OS_R65-10323.B-Vanilla.7z but when I click under icon, the notification ask me need logout and login again or update the OS, when I push update button on settings the system answer with no updates because is already updated, but still without open Play Store, so when I try to logout as notificatio say lost the video, and I have to type, ctr+alt+f2, to get tty2, and doing back ctrl+alt+f1 to recovery the GUI with login screen to login again, and stay in that loop. never open Play Store and ask me again to update the system.
any other suggestion? Is possible reinstall just Play Store by CLI or try other thing ?
thanks in advance.

**Comment by salembream** [comment] 2018-06-21 10:54
Did you find any fix?, I have similar issue

**Comment by arnoldthebat** [comment] 2018-09-10 17:54
Duplicate of #179

**Closed by arnoldthebat** 2018-09-10 17:54 UTC
