### ISSUE TITLE
TP LINK TL-WN725N not working on Camd64OS_R72-11316.B-Special build

### ISSUE THREAD

**Issue by krishnaprasad-gh** [arnoldthebat/chromiumos#246] opened 2019-02-11 07:31 UTC
hi Team,

I have installed Camd64OS_R72-11316.B-Special build on my Lenovo M58 desktop and HP Probook laptop.

Build was running but unable to detect the USB Wireless adapter.

I have tried the steps for Broadcom wireless driver fix at https://arnoldthebat.co.uk/wordpress/2013/02/24/how-to-get-the-broadcom-wireless-drivers-working/

but few commands like wget are not working, since wget is removed from chromium.

Can anyone help me with how to fix this issue.

**Comment by MuntashirAkon** [comment] 2019-03-11 06:53
Duplicate of #245

**Comment by arnoldthebat** [comment] 2019-09-30 17:46
Should be working in the latest alpha build released today. Please test and feedback.

**Closed by arnoldthebat** 2019-09-30 17:46 UTC
